### ISSUE TITLE
Allow passing `quality` to `jpeg-js`

### ISSUE THREAD

**Issue by twolfson** [scijs/save-pixels#13]
We currently support exporting images via `jpeg-js`. On occasion, I receive requests that `pixelsmith` tune `jpeg` quality upon export. I was wondering if we would be open to changing the function signature to accept options to pass along (e.g. `quality` for `jpeg-js`):

```js
savePixels(ndarray, 'jpeg', {quality: 50});
```

**Comment by twolfson** [comment]
Any thoughts on this?

**Comment by mikolalysenko** [comment]
One problem with this is that it would complicate the API a bit having an options structure in there.  That said, this might be pretty useful even for other image targets.  If you want to add something to it in a PR, I'll merge it in.

**Comment by twolfson** [comment]
Yea, you are right. It will need to some annoying `if/else` logic. I'm not sure I will be able to get to a PR by the end of this weekend so I will open a PR by the end of next weekend.

**Comment by twolfson** [comment]
Ah, I thought `type` was optional as in `get-pixels` but it isn't this makes the API much easier to manage =)
