### ISSUE TITLE
 deprecated pngjs2@1.2.0: pngjs2 has now taken over the original pngjs package on npm. Please change to use pngjs dependency, version 2+.

### ISSUE THREAD

**Issue by roninliu** [scijs/save-pixels#17]
deprecated pngjs2@1.2.0: pngjs2 has now taken over the original pngjs package on npm. Please change to use pngjs dependency, version 2+.

please update.. my componet has error

**Comment by CoralSilver** [comment]
+1 I'm having an issue with this as well.

**Comment by DarkPreacher** [comment]
+1 same issue here

**Comment by mikolalysenko** [comment]
Fixed
