### ISSUE TITLE
Flipped coordinates

### ISSUE THREAD

**Issue by dfcreative** [scijs/save-pixels#20]
Hi @mikolalysenko!
Whether I don’t understand something, or... I want to get simple 0→255 linear horizontal (left to right) gradient image, like this 
![grad-simple](https://cloud.githubusercontent.com/assets/300067/14549146/4a309c6e-028b-11e6-8898-0ab237cac74e.png).

I generate data and feed it into save-pixels:

```js
var ndarray = require("ndarray")
var savePixels = require("save-pixels")

//Create an image
var w = 20;
var h = 10;
var data = Array(w*h*4).fill(255);

data = data.map(function (value, i) {
	var result = 255 * ( Math.floor(i/4) % w) / (w-1);

	//catch alpha channel as 1, otherwise return grad   
	return (i+1) % 4 === 0 ? 255 : result;
});

var x = ndarray(data, [w, h, 4]);

//Save to a file
// document.body.appendChild(savePixels(x, "canvas"));
savePixels(x, "png").pipe(process.stdout);
```

In result I get: 
![png](https://cloud.githubusercontent.com/assets/300067/14549143/3e2746c0-028b-11e6-92c7-a0daed7ddff8.png)

I tried feeding that data array to ImageData of canvas2D, and it works alright:

```js
var canvas = document.createElement('canvas');
canvas.width = w;
canvas.height = h;
var ctx = canvas.getContext('2d');
var imageData = ctx.createImageData(w, h);

//copy generated above data to imageData
data.forEach(function (x, i) {
	imageData.data[i] = x;
});

//show canvas
ctx.putImageData(imageData, 0, 0);
document.body.appendChild(canvas);
```
![grad-simple](https://cloud.githubusercontent.com/assets/300067/14549146/4a309c6e-028b-11e6-8898-0ab237cac74e.png)

Is there a bug or something I don’t understand?

**Comment by mikolalysenko** [comment]
The issue here is a misunderstanding with how ndarray works.  By default ndarray uses row-major order, so it would generate a stride vector implicitly for that ndarary which is:

`[ h*4, 4, 1 ]`

But you want a stride vector that:

`[4, w*4, 1]`

If you just pass the stride in as the 3rd argument to the ndarray manually, then it should work as expected.

**Comment by dfcreative** [comment]
Ah, reasonable, thanks.
