### ISSUE TITLE
Gpu Rendering

### ISSUE THREAD

**Issue by GuillaumeLeclerc** [scijs/save-pixels#21]
Hello,

I made a WebGL renderer for images in the ndarray format. Would you be interested in having it here ?

**Comment by jywarren** [comment]
I'd be interested in using it, can you link?

**Comment by GuillaumeLeclerc** [comment]
I thought nobody was interested in it's in a private repo right now. For now it works with an ndarray of floats, a color map and the min and max for the color mapping. It also supports a convolution kernel of size 15. The only problem is it's quite slow to upload the ndarray to the GPU. So it is super useful but only if:

- you render multiple times the same data (using different strides or offset or length), if you want to zoom, pan or have multiple datasets in the same ndarray
- you need convolution filters 
- to want to change the color map and rerender (or change the bounds) 

If this is what you need tell me how you want to use it (es6 code, AMD bundle...)

**Comment by jywarren** [comment]
Thanks for writing back -- well, I'm not 100% sure, but am using `save-pixels` as part of this project which I may re-name: https://github.com/jywarren/imageboard/

it could help speed things up; if it were possible to do a one-line check for webGl capability and switch to your version if so, that'd be amazing -- so i guess if it conforms to the identical API would be the best. Thank you!

**Comment by GuillaumeLeclerc** [comment]
As I said, I don't think it would benefit your project as it is right now. First because it does not have the same API. My renderer accept a 2d ndarray, and a color map to map every value to a color. From what I understood your ndarray has a shape [x, y, 3] or maybe [x, y, 4] if you have alpha. 

I could adapt the code to work without a color map and three channels, but I'm not sure it would be useful. I tried your project and from what I understood what it does is for each step you do an operation on an nd array (ie generates a new one). that means for every step you would have to re-upload the ndarray to the GPU. Uploading data to the GPU is what takes most time. It usually takes more time than rendering on CPU side. This is why I said that rendering on GPU is only useful if you render multiple time the same data. I.E. you render the same ndarray but with different offset, strides, color map.

In any case I can give:

- Give you the code as it is (ES6 + Flow static checking, + 1 fragment shader + 1 vertexr shader) and let you play with it/adapt it to your needs.
- Try to adapt it to work with the `save-pixel` API and keep you update with the progress 

If I was working on that kind of project what I would certainly do is implement your filters on GPU side instead of just using the GPU to render the output. Although if your goal is to design a teaching tool then of course it make sense because students would have a very hard time debugging GPU code

**Comment by jywarren** [comment]
Hi - I see what you're saying, and I guess perhaps the last options makes
some sense, but I don't know how the step-wise modularity would work with
GPU code, or if it would at all. The idea in the (renamed) image-sequencer
lib is that each module is self contained, but I am thinking about how to
avoid re-encoding images over and over:

https://github.com/jywarren/image-sequencer/issues/1

**Comment by GuillaumeLeclerc** [comment]
If you were working with GPU you could just store the pictures as textures. 
Each of your module would define a shader (piece of code that processes textures), and your code could provide references to the previous texture. The big advantage I see is that you would never have to reencode it. The only disadvantage I may see is that each module would only be able to access the k-previous images in the pipeline because of WebGL limitations (but k >= 8 on any GPU).

If you need any advice that is not related to this issue feel free to contact me on my email !

**Comment by benwiley4000** [comment]
Hey @GuillaumeLeclerc - I'm going to close this issue since it looks like this isn't happening, but let me know if you think it should be re-opened! 🙂
