### ISSUE TITLE
how can I save rgba pixels data.

### ISSUE THREAD

**Issue by programmerpsk** [scijs/save-pixels#26]
I put rgba pixels data of image in your library.
but there are wrong return data.. (It's like Gray-scale and striped image anyway something strange..)
how I can use rgba pixels data in this module??

**Comment by lqs469** [comment]
@programmerpsk
`.set(x, y, rgb, value)`
```
// x, y => red
p.set(x, y, 0, 255)
p.set(x, y, 1, 0)
p.set(x, y, 2, 0)
```

**Comment by independentgeorge** [comment]
@lqs469 How does that answer the question? Where is the alpha channel?

**Comment by lqs469** [comment]
@independentgeorge I do not understand what you mean

**Comment by independentgeorge** [comment]
The question was about supporting [RGBA](https://en.wikipedia.org/wiki/RGBA_color_space) and your comment is about [RGB](https://en.wikipedia.org/wiki/RGB_color_model).

**Comment by lqs469** [comment]
@independentgeorge Same as example: `.set(i, j, 3, value)`
